export type MarketingPageKind = "career-ops" | "role" | "industry";

export type MarketingPage = {
  kind: MarketingPageKind;
  slug: string;
  path: string;
  eyebrow: string;
  title: string;
  description: string;
  audience: string;
  promise: string;
  keywords: string[];
  workflows: string[];
  proofPoints: string[];
};

export const rolePages: MarketingPage[] = [
  {
    kind: "role",
    slug: "product-marketing-jobs-singapore",
    path: "/roles/product-marketing-jobs-singapore",
    eyebrow: "Role playbook",
    title: "Product Marketing Jobs Singapore Career Ops",
    description: "Use JobPA to track, tailor, and improve every Product Marketing application in Singapore with AI fit scoring and resume positioning.",
    audience: "For PMM, GTM, growth, lifecycle, and launch candidates targeting Singapore tech, fintech, SaaS, and AI startup roles.",
    promise: "Turn each Product Marketing JD into a positioning brief, fit score, resume gap list, and next action.",
    keywords: ["product marketing jobs Singapore", "PMM Singapore", "go-to-market jobs", "launch strategy", "career ops", "AI career assistant"],
    workflows: ["Map JD requirements to PMM stories", "Tailor achievement bullets by product, market, and metric", "Track application status and follow-up timing"],
    proofPoints: ["Resume analysis", "Job fit score", "Application tracker"],
  },
  {
    kind: "role",
    slug: "customer-success-jobs-singapore",
    path: "/roles/customer-success-jobs-singapore",
    eyebrow: "Role playbook",
    title: "Customer Success Jobs Singapore Career Ops",
    description: "Run a stronger Customer Success job search in Singapore with AI-assisted resume tailoring, fit scoring, and pipeline follow-ups.",
    audience: "For CSM, account manager, onboarding, renewals, implementation, and client-facing candidates.",
    promise: "Show retention, adoption, stakeholder management, and customer outcomes clearly in every application.",
    keywords: ["customer success jobs Singapore", "CSM Singapore", "account management", "renewals", "onboarding", "AI career assistant"],
    workflows: ["Extract customer impact metrics", "Match CS motion to each job description", "Prepare interview stories around adoption and retention"],
    proofPoints: ["Profile memory", "Interview prep", "Email center"],
  },
  {
    kind: "role",
    slug: "business-analyst-career-ops",
    path: "/roles/business-analyst-career-ops",
    eyebrow: "Role playbook",
    title: "Business Analyst Career Ops",
    description: "Build a focused Business Analyst pipeline with AI support for requirements, analytics, stakeholder, and operations-heavy roles.",
    audience: "For business analysts, operations analysts, strategy analysts, PMO, and transformation candidates.",
    promise: "Translate projects into measurable business outcomes and match them to each hiring signal.",
    keywords: ["business analyst career ops", "business analyst jobs Singapore", "operations analyst", "requirements", "process improvement"],
    workflows: ["Score role fit against projects and tools", "Surface missing domain keywords", "Create follow-up tasks for each opportunity"],
    proofPoints: ["Career Ops scan", "Checklist", "Reports"],
  },
  {
    kind: "role",
    slug: "marketing-analytics-jobs-singapore",
    path: "/roles/marketing-analytics-jobs-singapore",
    eyebrow: "Role playbook",
    title: "Marketing Analytics Jobs Singapore Career Ops",
    description: "Target marketing analytics roles with AI-assisted keyword mapping across CRM, lifecycle, performance, and data storytelling.",
    audience: "For marketing analysts, growth analysts, CRM analysts, and lifecycle marketers.",
    promise: "Turn campaigns, dashboards, and experiments into role-specific evidence.",
    keywords: ["marketing analytics jobs Singapore", "CRM analyst Singapore", "growth analyst", "lifecycle marketing", "data storytelling"],
    workflows: ["Map tools and metrics to JD language", "Build quantified resume variants", "Track interview-stage signals"],
    proofPoints: ["Resume parser", "Job fit", "Industry trends"],
  },
  {
    kind: "role",
    slug: "pre-sales-jobs-singapore",
    path: "/roles/pre-sales-jobs-singapore",
    eyebrow: "Role playbook",
    title: "Pre-Sales Jobs Singapore Career Ops",
    description: "Position technical and business experience for pre-sales, solutions consulting, and revenue-facing AI roles.",
    audience: "For pre-sales, solutions consultant, sales engineer, and business development candidates.",
    promise: "Connect discovery, demos, stakeholder management, and commercial impact into one application workflow.",
    keywords: ["pre-sales jobs Singapore", "solutions consultant Singapore", "sales engineering", "discovery", "demo"],
    workflows: ["Build role-specific proof of consultative selling", "Prepare demo and objection stories", "Prioritize accounts and industries"],
    proofPoints: ["AI chat", "Interview prep", "Application tracker"],
  },
  {
    kind: "role",
    slug: "strategy-consultant-jobs-singapore",
    path: "/roles/strategy-consultant-jobs-singapore",
    eyebrow: "Role playbook",
    title: "Strategy Consultant Jobs Singapore Career Ops",
    description: "Use JobPA to position PMO, operations, consulting, and business transformation experience for Singapore strategy roles.",
    audience: "For international candidates targeting strategy consulting, business operations, transformation, and in-house strategy teams.",
    promise: "Turn project delivery into crisp problem, action, result proof that hiring teams can evaluate quickly.",
    keywords: ["strategy consultant jobs Singapore", "business strategy consultant", "transformation consultant", "PMO Singapore", "career ops"],
    workflows: ["Convert PMO projects into quantified business outcomes", "Map consulting keywords to each JD", "Track networking, follow-ups, and case interview prep"],
    proofPoints: ["Interview prep", "Resume analysis", "Career pipeline"],
  },
  {
    kind: "role",
    slug: "business-operations-jobs-singapore",
    path: "/roles/business-operations-jobs-singapore",
    eyebrow: "Role playbook",
    title: "Business Operations Jobs Singapore Career Ops",
    description: "Run a structured job search for Business Operations, Revenue Ops, Strategy Ops, and Program Manager roles in Singapore.",
    audience: "For candidates moving from PMO, operations, consulting, startup, or analyst backgrounds into high-growth business teams.",
    promise: "Connect process, systems, stakeholder, and revenue impact to each role's hiring signal.",
    keywords: ["business operations jobs Singapore", "revenue operations", "strategy operations", "program manager Singapore", "career ops"],
    workflows: ["Score role fit by operating model", "Tailor bullets around systems and measurable impact", "Move priority roles through a tracked follow-up cadence"],
    proofPoints: ["Career Ops scan", "Reports", "Application tracker"],
  },
];

export const industryPages: MarketingPage[] = [
  {
    kind: "industry",
    slug: "tech",
    path: "/industries/tech",
    eyebrow: "Industry playbook",
    title: "Tech Career Ops",
    description: "Use JobPA to run a tech job search across product, marketing, customer, data, operations, and engineering-adjacent roles.",
    audience: "For candidates targeting startups, SaaS, platforms, AI products, cloud teams, and enterprise technology companies.",
    promise: "Translate technical fluency and business impact into role-specific applications.",
    keywords: ["tech jobs Singapore", "AI jobs", "SaaS jobs", "product jobs", "career ops"],
    workflows: ["Map technical and business keywords", "Tailor proof by product stage", "Track interviews and follow-ups by company"],
    proofPoints: ["Dashboard preview", "Resume variants", "Job fit"],
  },
  {
    kind: "industry",
    slug: "fintech",
    path: "/industries/fintech",
    eyebrow: "Industry playbook",
    title: "Fintech Career Ops",
    description: "Run a fintech job search with AI support for product, risk, growth, compliance, analytics, and customer-facing roles.",
    audience: "For candidates targeting banks, payments, wealth, crypto, insurtech, and embedded finance teams.",
    promise: "Translate domain context and measurable outcomes into stronger fintech applications.",
    keywords: ["fintech", "payments", "banking", "risk", "compliance"],
    workflows: ["Track fintech-specific requirements", "Map domain keywords into resume variants", "Prepare market-aware interview stories"],
    proofPoints: ["Industry trends", "Job fit", "Reports"],
  },
  {
    kind: "industry",
    slug: "finance",
    path: "/industries/finance",
    eyebrow: "Industry playbook",
    title: "Finance Career Ops",
    description: "Target banking, payments, wealth, risk, analytics, and operations roles with a structured AI-assisted application pipeline.",
    audience: "For candidates applying to banks, fintechs, insurers, wealth platforms, and finance transformation teams.",
    promise: "Make compliance, stakeholder, analytics, and commercial outcomes visible in each application.",
    keywords: ["finance jobs Singapore", "banking jobs", "risk analyst", "finance operations", "career ops"],
    workflows: ["Map finance-domain keywords", "Build quantified impact bullets", "Prepare market-aware interview answers"],
    proofPoints: ["Industry trends", "Job fit", "Reports"],
  },
  {
    kind: "industry",
    slug: "saas",
    path: "/industries/saas",
    eyebrow: "Industry playbook",
    title: "SaaS Career Ops",
    description: "Target SaaS roles with structured tracking across GTM, product, CS, growth, data, and operations positions.",
    audience: "For candidates applying to B2B SaaS startups, scaleups, and enterprise software teams.",
    promise: "Make ARR, activation, retention, and product adoption signals visible in each application.",
    keywords: ["SaaS", "B2B", "GTM", "retention", "activation"],
    workflows: ["Convert projects into SaaS metrics", "Tailor bullets by product maturity", "Track follow-ups by stage"],
    proofPoints: ["Career Ops", "Email center", "Checklist"],
  },
  {
    kind: "industry",
    slug: "marketing",
    path: "/industries/marketing",
    eyebrow: "Industry playbook",
    title: "Marketing Career Ops",
    description: "Run marketing applications across product marketing, growth, lifecycle, brand, CRM, content, and analytics with JobPA.",
    audience: "For marketers who need stronger positioning, quantified campaign proof, and role-specific resume variants.",
    promise: "Turn campaign work into business outcomes that match each JD.",
    keywords: ["marketing jobs Singapore", "product marketing", "growth marketing", "CRM marketing", "career ops"],
    workflows: ["Translate campaigns into metrics", "Tailor proof by channel and funnel", "Track interviews and content tasks"],
    proofPoints: ["Resume analysis", "Email center", "Dashboard"],
  },
  {
    kind: "industry",
    slug: "sales",
    path: "/industries/sales",
    eyebrow: "Industry playbook",
    title: "Sales Career Ops",
    description: "Position sales, business development, account management, and solutions experience for Singapore and regional roles.",
    audience: "For candidates targeting BDR, AE, AM, partnerships, pre-sales, and revenue operations paths.",
    promise: "Show quota, pipeline, discovery, stakeholder, and revenue outcomes clearly.",
    keywords: ["sales jobs Singapore", "business development", "account executive", "pre-sales", "career ops"],
    workflows: ["Extract revenue proof", "Map sales motion to JD language", "Prepare interview stories and follow-up emails"],
    proofPoints: ["Interview prep", "Email center", "Application tracker"],
  },
  {
    kind: "industry",
    slug: "hr",
    path: "/industries/hr",
    eyebrow: "Industry playbook",
    title: "HR Career Ops",
    description: "Use JobPA to target HR, people operations, talent acquisition, L&D, and HR analytics roles with structured applications.",
    audience: "For candidates moving into people teams, employee experience, TA operations, or HR business partnering.",
    promise: "Translate people programs and stakeholder work into measurable hiring signals.",
    keywords: ["HR jobs Singapore", "people operations", "talent acquisition", "HR analytics", "career ops"],
    workflows: ["Map HR competencies to each JD", "Quantify people program outcomes", "Track hiring-stage tasks and follow-ups"],
    proofPoints: ["Profile memory", "Reports", "AI chat"],
  },
  {
    kind: "industry",
    slug: "consulting",
    path: "/industries/consulting",
    eyebrow: "Industry playbook",
    title: "Consulting Career Ops",
    description: "Prepare consulting applications with AI help for case stories, client impact, market research, and structured achievements.",
    audience: "For strategy, management, technology, operations, and boutique consulting candidates.",
    promise: "Turn ambiguous experience into crisp problem, action, result stories.",
    keywords: ["consulting", "strategy", "client impact", "case interview", "transformation"],
    workflows: ["Build STAR stories from projects", "Map client outcomes to role requirements", "Plan interview preparation tasks"],
    proofPoints: ["Interview prep", "Resume analysis", "Reports"],
  },
  {
    kind: "industry",
    slug: "healthcare",
    path: "/industries/healthcare",
    eyebrow: "Industry playbook",
    title: "Healthcare Career Ops",
    description: "Position healthcare, healthtech, and life sciences experience for product, operations, analytics, and customer-facing jobs.",
    audience: "For candidates targeting healthtech, hospitals, pharma, medtech, and wellness companies.",
    promise: "Highlight regulated-domain judgment, patient or customer impact, and cross-functional work.",
    keywords: ["healthcare", "healthtech", "medtech", "operations", "analytics"],
    workflows: ["Identify domain-specific evidence", "Tailor resume language for regulated teams", "Track role fit by business function"],
    proofPoints: ["Industry trends", "Job fit", "AI chat"],
  },
  {
    kind: "industry",
    slug: "ai-startups",
    path: "/industries/ai-startups",
    eyebrow: "Industry playbook",
    title: "AI Startup Career Ops",
    description: "Use JobPA to target AI startup roles across product, growth, operations, customer success, analytics, and technical teams.",
    audience: "For candidates who need to show AI fluency without being boxed into only engineering roles.",
    promise: "Connect AI literacy, business impact, and execution speed to each role.",
    keywords: ["AI startup", "agentic AI", "growth", "product", "operations"],
    workflows: ["Map AI-related skills to non-tech roles", "Build concise startup-ready resume variants", "Prioritize high-signal opportunities"],
    proofPoints: ["Career Ops scan", "Profile memory", "Dashboard"],
  },
];

export const careerOpsPage: MarketingPage = {
  kind: "career-ops",
  slug: "career-ops",
  path: "/career-ops",
  eyebrow: "Agentic AI Career Ops",
  title: "AI Career Ops that tracks, tailors, and improves every application",
  description: "JobPA is agentic AI Career Ops with an AI Career Assistant for international job seekers: scan roles, score fit, tailor resumes, track applications, and keep every next step moving.",
  audience: "For candidates managing cross-border applications, multiple role tracks, and fast-moving hiring pipelines.",
  promise: "One workflow for job discovery, resume intelligence, fit scoring, application tracking, interview preparation, and paid consulting when you need human help.",
  keywords: ["agentic AI career ops", "AI career assistant", "career ops", "job search operating system", "resume tailoring", "application tracking"],
  workflows: ["Scan opportunities with fit and visa signals", "Generate role-specific resume gaps and action plans", "Move selected roles into a tracked pipeline"],
  proofPoints: ["23 applications tracked in the dashboard preview", "Resume and job fit analysis", "Career Ops agent queue"],
};

export const marketingPages = [careerOpsPage, ...rolePages, ...industryPages];

export function getMarketingPageByPath(pathname: string) {
  const normalized = pathname.replace(/\/+$/, "") || "/";
  return marketingPages.find((page) => page.path === normalized) ?? careerOpsPage;
}
