import * as db from "./db";
import { applicationAgent, jobDiscoveryAgent, jobFitAgent, marketVisaAgent } from "./agents";
import {
  createJobFitEvaluation,
  fetchJobs,
  getUserProfile,
  saveJob,
} from "./jobpaAdapter";
import type { JobListing } from "./jobFetcher";

type CareerOpsInput = {
  search?: string;
  location?: string;
  limit?: number;
};

type ManualEvaluationInput = {
  jobTitle?: string;
  company?: string;
  jobDescription: string;
  targetRole?: string;
};

const SOURCE_POLICY =
  "Career Ops in JobPA uses approved APIs, cached database records, or sanitized demo jobs. It does not auto-apply or scrape job boards without explicit approval.";

function clampLimit(limit?: number) {
  return Math.max(3, Math.min(limit ?? 10, 20));
}

function careerOpsGrade(score: number) {
  if (score >= 90) return "A";
  if (score >= 85) return "A-";
  if (score >= 80) return "B+";
  if (score >= 75) return "B";
  if (score >= 70) return "B-";
  if (score >= 65) return "C+";
  if (score >= 60) return "C";
  if (score >= 50) return "D";
  return "F";
}

function decisionForScore(score: number) {
  if (score >= 80) {
    return {
      level: "priority" as const,
      label: "Priority target",
      summary: "Strong match. Save it, tailor the resume, and decide whether to apply within 48 hours.",
    };
  }
  if (score >= 65) {
    return {
      level: "consider" as const,
      label: "Consider with tailoring",
      summary: "Potential match. Apply only if the gaps can be handled truthfully in resume and cover note.",
    };
  }
  if (score >= 55) {
    return {
      level: "hold" as const,
      label: "Hold for research",
      summary: "Possible but weak. Research the team or find a warm path before spending application time.",
    };
  }
  return {
    level: "skip" as const,
    label: "Skip for now",
    summary: "Low match. Keep this as market signal unless there is a strategic reason to pursue it.",
  };
}

function toStringList(value: unknown, fallback: string[] = []) {
  return Array.isArray(value) ? value.filter(item => typeof item === "string") : fallback;
}

function getResumeStrengths(resumeAnalysis: Record<string, any> | null | undefined) {
  const direct = toStringList(resumeAnalysis?.strengths);
  const raw = toStringList(resumeAnalysis?.rawResult?.strengths);
  return (direct.length > 0 ? direct : raw).slice(0, 4);
}

function profileSkills(profile: Record<string, any> | null | undefined) {
  const skills = toStringList(profile?.skills);
  const interests = toStringList(profile?.interests);
  return Array.from(new Set([...skills, ...interests])).slice(0, 10);
}

function buildResumeVariant(input: {
  profile: Record<string, any> | null;
  resumeAnalysis: Record<string, any> | null;
  jobTitle?: string;
  company?: string;
  targetRole?: string;
  fitResult: Record<string, any>;
}) {
  const role = input.jobTitle || input.targetRole || input.profile?.targetRole || "target role";
  const company = input.company || "target company";
  const matchedSkills = toStringList(input.fitResult.matchedSkills);
  const missingSkills = toStringList(input.fitResult.missingSkills);
  const strengths = getResumeStrengths(input.resumeAnalysis);
  const skills = Array.from(new Set([...profileSkills(input.profile), ...matchedSkills])).slice(0, 12);
  const market = input.profile?.targetLocation || input.profile?.market || "target market";

  const markdown = `# Tailored Resume Variant - ${role}

Company: ${company}
Market: ${market}
Generated by JobPA Career Ops

AI guidance only. Use this as a truthful tailoring draft, not a guarantee of interview, employment, salary, or visa outcome.

## Positioning Summary
Position yourself as a ${role} candidate for ${company}. Lead with the strongest evidence that overlaps with the job description, then make work status, location fit, and availability easy to understand.

## Keywords To Mirror Truthfully
${skills.length > 0 ? skills.map(skill => `- ${skill}`).join("\n") : "- Add role-specific keywords from the job description after verifying they are true to your experience."}

## Proof Points To Move Up
${strengths.length > 0 ? strengths.map(item => `- ${item}`).join("\n") : "- Add 2-3 quantified achievements tied to growth, efficiency, customer outcomes, revenue, cost, quality, or delivery speed."}

## Gaps To Handle Honestly
${missingSkills.length > 0 ? missingSkills.map(skill => `- ${skill}: add truthful evidence, a learning plan, or leave it out if you do not have it.`).join("\n") : "- No major keyword gaps detected. Keep the resume concise and specific."}

## Cover Note Angle
Open with why this role, why this company, and one measurable result that proves you can do the work. Keep the note under 180 words.

## Interview Prep Hooks
- Prepare a 90-second career story for ${role}.
- Prepare STAR stories for ownership, measurable impact, ambiguity, and stakeholder conflict.
- Prepare two company-specific questions about success metrics and team operating rhythm.
`;

  return {
    title: `${role} at ${company}`,
    markdown,
    keywords: skills,
    gaps: missingSkills,
  };
}

function normalizeJobDescription(job: JobListing) {
  const skills = (job.skills ?? []).join(", ");
  return [job.description, skills ? `Skills: ${skills}` : "", `Role: ${job.title}`, `Company: ${job.company}`]
    .filter(Boolean)
    .join("\n\n");
}

async function persistAgentTask(input: {
  userId: number;
  taskType: string;
  status: "success" | "partial" | "failed";
  request: unknown;
  output?: unknown;
  errorMessage?: string;
}) {
  await db.recordAgentTask({
    userId: input.userId,
    agent: "Career Ops Agent",
    taskType: input.taskType,
    status: input.status,
    input: input.request,
    output: input.output,
    errorMessage: input.errorMessage,
  }).catch(() => undefined);
}

export async function runCareerOpsScan(userId: number, input: CareerOpsInput) {
  const limit = clampLimit(input.limit);
  const [profile, latestResume] = await Promise.all([
    getUserProfile(userId).catch(() => null),
    db.getLatestResumeAnalysis(userId).catch(() => null),
  ]);

  const resumeContext = (latestResume ?? null) as Record<string, any> | null;
  const targetRole = String(input.search?.trim() || profile?.targetRole || "product manager");
  const location = input.location && input.location !== "all" ? input.location : (profile?.targetLocation ?? undefined);
  const search = targetRole;
  const jobData = await fetchJobs({ search, location, limit: Math.max(limit * 2, 12) });
  const ranked = jobDiscoveryAgent.rankJobs(jobData.jobs, profile).slice(0, limit);

  const evaluations = [];
  for (const job of ranked) {
    const fit = jobFitAgent.evaluate({
      profile,
      resumeAnalysis: resumeContext,
      targetRole,
      jobTitle: job.title,
      company: job.company,
      jobDescription: normalizeJobDescription(job),
    });
    const blendedScore = Math.round((fit.fitScore * 0.8) + (((job as any).matchScore ?? 50) * 0.2));
    const grade = careerOpsGrade(blendedScore);
    const decision = decisionForScore(blendedScore);
    const result = {
      ...(fit.result ?? {}),
      fitScore: blendedScore,
      grade,
      decision,
      sourcePolicy: SOURCE_POLICY,
      jobDiscoveryScore: (job as any).matchScore ?? null,
    };

    await createJobFitEvaluation(userId, {
      jobId: job.id,
      targetRole,
      jobTitle: job.title,
      company: job.company,
      jobDescription: normalizeJobDescription(job),
      fitScore: blendedScore,
      status: "success",
      result,
    }).catch(() => undefined);

    evaluations.push({
      job,
      fitScore: blendedScore,
      grade,
      decision,
      matchedSkills: fit.result.matchedSkills ?? [],
      missingSkills: fit.result.missingSkills ?? [],
      strategy: fit.result.strategy ?? [],
      interviewTips: fit.result.interviewTips ?? [],
      resumeVariant: buildResumeVariant({
        profile,
        resumeAnalysis: resumeContext,
        jobTitle: job.title,
        company: job.company,
        targetRole,
        fitResult: result,
      }),
    });
  }

  const output = {
    mode: jobData.mode,
    message: jobData.message,
    sources: jobData.sources,
    sourcePolicy: SOURCE_POLICY,
    search,
    location: location || "all",
    resumeStatus: resumeContext ? "available" : "missing",
    marketGuidance: marketVisaAgent.guidance(location || profile?.targetLocation || "singapore"),
    nextActions: evaluations.length > 0
      ? [
          "Save A/B-grade roles before applying.",
          "Download the tailored resume draft and edit it truthfully.",
          "Move only selected roles into Applications Tracker.",
        ]
      : [
          "Complete My Profile or broaden the search query.",
          "Paste a JD manually for evaluation.",
          "Check approved job APIs or cached data availability.",
        ],
    evaluations,
  };

  await persistAgentTask({
    userId,
    taskType: "career_ops_scan",
    status: evaluations.length > 0 ? "success" : "partial",
    request: input,
    output,
  });

  return output;
}

export async function evaluateManualJob(userId: number, input: ManualEvaluationInput) {
  const [profile, latestResume] = await Promise.all([
    getUserProfile(userId).catch(() => null),
    db.getLatestResumeAnalysis(userId).catch(() => null),
  ]);

  const resumeContext = (latestResume ?? null) as Record<string, any> | null;
  const targetRole = input.targetRole || (profile?.targetRole ? String(profile.targetRole) : undefined);
  const role = input.jobTitle || targetRole || "Pasted job description";
  const company = input.company || "Manual JD";
  const fit = jobFitAgent.evaluate({
    profile,
    resumeAnalysis: resumeContext,
    targetRole,
    jobTitle: role,
    company,
    jobDescription: input.jobDescription,
  });
  const grade = careerOpsGrade(fit.fitScore);
  const decision = decisionForScore(fit.fitScore);
  const result = {
    ...(fit.result ?? {}),
    grade,
    decision,
    sourcePolicy: SOURCE_POLICY,
  };

  await createJobFitEvaluation(userId, {
    targetRole,
    jobTitle: role,
    company,
    jobDescription: input.jobDescription,
    fitScore: fit.fitScore,
    status: "success",
    result,
  }).catch(() => undefined);

  const output = {
    job: {
      id: `manual-${Date.now()}`,
      title: role,
      company,
      location: profile?.targetLocation || "manual",
      source: "manual",
      applyUrl: "#",
      visa: false,
      type: "fulltime",
      experience: profile?.experienceLevel || "mid",
      industry: "manual",
      posted: 0,
      remote: false,
      description: input.jobDescription,
      skills: [],
    },
    fitScore: fit.fitScore,
    grade,
    decision,
    matchedSkills: fit.result.matchedSkills ?? [],
    missingSkills: fit.result.missingSkills ?? [],
    strategy: fit.result.strategy ?? [],
    interviewTips: fit.result.interviewTips ?? [],
    resumeVariant: buildResumeVariant({
      profile,
      resumeAnalysis: resumeContext,
      jobTitle: role,
      company,
      targetRole,
      fitResult: result,
    }),
    sourcePolicy: SOURCE_POLICY,
    nextActions: applicationAgent.nextActions("bookmarked"),
  };

  await persistAgentTask({
    userId,
    taskType: "career_ops_manual_jd",
    status: "success",
    request: { ...input, jobDescription: input.jobDescription.slice(0, 4000) },
    output,
  });

  return output;
}

export async function saveCareerOpsJob(userId: number, input: { job: JobListing; notes?: string }) {
  return saveJob(userId, input.job, input.notes || "Saved from Career Ops Center");
}
