import type { JobListing } from "./jobFetcher";

export const DEMO_JOBS: JobListing[] = [
  {
    id: "demo-sg-ai-marketing-001",
    title: "AI Marketing Analyst",
    company: "Merlion Growth Labs",
    location: "singapore",
    salary: "S$5,500-7,500/mo",
    source: "other",
    applyUrl: "https://example.com/demo/ai-marketing-analyst",
    visa: true,
    type: "fulltime",
    experience: "junior",
    industry: "marketing",
    posted: 2,
    remote: false,
    description:
      "Use customer, campaign, and product data to improve regional growth programs across Singapore and Southeast Asia.",
    closingDate: "Demo listing",
    employmentType: "Full-time",
    skills: ["SQL", "Marketing Analytics", "Dashboarding", "Generative AI"],
  },
  {
    id: "demo-hk-growth-002",
    title: "Growth Strategy Associate",
    company: "Harbour Fintech Studio",
    location: "hongkong",
    salary: "HK$32,000-45,000/mo",
    source: "other",
    applyUrl: "https://example.com/demo/growth-strategy-associate",
    visa: true,
    type: "fulltime",
    experience: "junior",
    industry: "finance",
    posted: 4,
    remote: false,
    description:
      "Support go-to-market experiments, customer research, and strategic partnerships for a cross-border fintech product.",
    closingDate: "Demo listing",
    employmentType: "Full-time",
    skills: ["Market Research", "Partnerships", "Fintech", "Excel"],
  },
  {
    id: "demo-dubai-pm-003",
    title: "Associate Product Manager",
    company: "Desert Cloud Commerce",
    location: "dubai",
    salary: "AED 14,000-20,000/mo",
    source: "other",
    applyUrl: "https://example.com/demo/associate-product-manager",
    visa: true,
    type: "fulltime",
    experience: "mid",
    industry: "ecommerce",
    posted: 5,
    remote: false,
    description:
      "Own product discovery, analytics, and launch coordination for a commerce platform serving GCC merchants.",
    closingDate: "Demo listing",
    employmentType: "Full-time",
    skills: ["Product Analytics", "Roadmapping", "User Research", "SQL"],
  },
  {
    id: "demo-kr-global-brand-004",
    title: "Global Brand Operations Specialist",
    company: "Seoul Consumer Tech",
    location: "korea",
    salary: "KRW 4.2M-6.0M/mo",
    source: "other",
    applyUrl: "https://example.com/demo/global-brand-operations",
    visa: false,
    type: "fulltime",
    experience: "junior",
    industry: "marketing",
    posted: 7,
    remote: false,
    description:
      "Coordinate English-language brand operations, creator campaigns, and overseas launch assets for a Korean consumer tech team.",
    closingDate: "Demo listing",
    employmentType: "Full-time",
    skills: ["Korean", "English", "Creator Marketing", "Operations"],
  },
  {
    id: "demo-remote-data-005",
    title: "Remote Data Storytelling Consultant",
    company: "Open Career Analytics",
    location: "remote",
    salary: "USD 45-65/hr",
    source: "other",
    applyUrl: "https://example.com/demo/data-storytelling-consultant",
    visa: false,
    type: "contract",
    experience: "mid",
    industry: "tech",
    posted: 1,
    remote: true,
    description:
      "Turn messy customer and market datasets into executive-ready dashboards, narratives, and weekly decision briefs.",
    closingDate: "Demo listing",
    employmentType: "Contract",
    skills: ["Data Visualization", "Storytelling", "Tableau", "Python"],
  },
];

export const DEMO_CHECKLIST = [
  "Complete career profile with target country, role, salary, and visa status",
  "Upload a resume or paste resume text for analysis",
  "Save three target jobs and run one job fit evaluation",
  "Move one application through the tracker and generate interview prep",
  "Generate a weekly career management report",
];

export const DEMO_PROFILE = {
  targetRole: "AI Marketing Analyst",
  targetCountries: ["singapore", "hongkong"],
  experienceLevel: "junior",
  salaryRange: "S$5,500-7,500/mo",
  visaStatus: "Needs employer sponsorship",
  preferredLanguage: "English",
  interests: ["AI/ML", "Marketing Analytics", "Product Growth"],
};
